export const WORLD_TAB_LABEL = "Compétition";
export const WORLD_TITLE = "Compétition";
export const LEADERBOARD_EMPTY = "Personne n'est encore classé ce mois-ci.";
export const LEADERBOARD_ERROR = "Impossible de charger le classement.";
export const PAGER_FIRST_LABEL = "Début";
export const PAGER_PREVIOUS_LABEL = "Page précédente";
export const PAGER_NEXT_LABEL = "Page suivante";
export const PAGER_LAST_LABEL = "Fin";
export const PAGER_MY_PAGE_LABEL = "Ma page";
